export const shopCategories = [
    { value: 'electronics', label: 'Electronics' },
    { value: 'fashion', label: 'Fashion & Apparel' },
    { value: 'home_garden', label: 'Home & Garden' },
    { value: 'beauty_health', label: 'Beauty & Health' },
    { value: 'sports_outdoors', label: 'Sports & Outdoors' },
    { value: 'toys_games', label: 'Toys & Games' },
    { value: 'automotive', label: 'Automotive' },
    { value: 'books', label: 'Books & Stationary' },
    { value: 'groceries', label: 'Groceries & Gourmet' },
    { value: 'baby_kids', label: 'Baby & Kids' },
    { value: 'jewelry', label: 'Jewelry & Accessories' },
    { value: 'pet_supplies', label: 'Pet Supplies' },
    { value: 'office_supplies', label: 'Office Supplies' },
    { value: 'music_movies', label: 'Music & Movies' },
    { value: 'tools_hardware', label: 'Tools & Hardware' },
    { value: 'art_crafts', label: 'Art & Crafts' },
    { value: 'footwear', label: 'Footwear' },
    { value: 'bags_luggage', label: 'Bags & Luggage' },
    { value: 'mobile_accessories', label: 'Mobile & Accessories' },
    { value: 'computers', label: 'Computers & Peripherals' },
    { value: 'appliances', label: 'Appliances' },
    { value: 'furniture', label: 'Furniture' },
    { value: 'watches', label: 'Watches' },
    { value: 'gaming', label: 'Gaming' },
    { value: 'stationery', label: 'Stationery' },
    { value: 'travel', label: 'Travel & Outdoor Gear' },
    { value: 'collectibles', label: 'Collectibles & Memorabilia' },
    { value: 'industrial', label: 'Industrial & Scientific' }
];